# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-18 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_star', models.BooleanField(choices=[(0, '未星标'), (1, '星标')])),
            ],
        ),
        migrations.CreateModel(
            name='PriceStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('price', models.IntegerField(verbose_name='价格/年')),
                ('number', models.IntegerField(verbose_name='项目数量')),
                ('member', models.IntegerField(verbose_name='项目成员')),
                ('space_size', models.IntegerField(verbose_name='每个项目空间大小')),
                ('single_size', models.IntegerField(verbose_name='单文件大小')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='项目标题')),
                ('desc', models.TextField(verbose_name='项目描述')),
                ('color', models.CharField(max_length=20, verbose_name='背景颜色')),
                ('is_star', models.BooleanField(choices=[(0, '未星标'), (1, '星标')])),
                ('member_num', models.SmallIntegerField(verbose_name='成员数量')),
                ('used_space', models.CharField(max_length=20, verbose_name='已用空间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='创建者')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(0, '未支付'), (1, '已支付')])),
                ('actual_payment', models.CharField(max_length=20, verbose_name='实际支付')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('number', models.SmallIntegerField(verbose_name='购买数量(年)')),
                ('order', models.CharField(max_length=100, verbose_name='订单编号')),
                ('price_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.PriceStrategy', verbose_name='价格策略类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='支付的用户')),
            ],
        ),
        migrations.AddField(
            model_name='participants',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Projects', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='participants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo', verbose_name='用户'),
        ),
    ]
