# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-18 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200318_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricestrategy',
            name='single_size',
            field=models.IntegerField(verbose_name='单文件大小(MB)'),
        ),
        migrations.AlterField(
            model_name='pricestrategy',
            name='space_size',
            field=models.IntegerField(verbose_name='每个项目空间大小(MB)'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='color',
            field=models.SmallIntegerField(choices=[(1, '#FFDAB9'), (2, '\t#00E5EE'), (3, '#E6E6FA'), (4, '#8470FF'), (5, '#FF6A6A'), (6, '#00BFFF')], verbose_name='背景颜色'),
        ),
    ]
