# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-18 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200318_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='is_star',
            field=models.BooleanField(choices=[(0, '未星标'), (1, '星标')], default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='member_num',
            field=models.SmallIntegerField(default=1, verbose_name='成员数量'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='used_space',
            field=models.CharField(default=0, max_length=20, verbose_name='已用空间'),
        ),
    ]
