# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-18 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200318_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='项目描述'),
        ),
    ]
