# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-19 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200318_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='member_num',
            new_name='join_count',
        ),
        migrations.RenameField(
            model_name='transactionrecord',
            old_name='number',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='pricestrategy',
            name='member',
        ),
        migrations.RemoveField(
            model_name='pricestrategy',
            name='number',
        ),
        migrations.RemoveField(
            model_name='pricestrategy',
            name='single_size',
        ),
        migrations.RemoveField(
            model_name='pricestrategy',
            name='space_size',
        ),
        migrations.AddField(
            model_name='participants',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricestrategy',
            name='category',
            field=models.SmallIntegerField(choices=[(1, '免费版 '), (2, '收费版'), (3, '其他')], default=1),
        ),
        migrations.AddField(
            model_name='pricestrategy',
            name='per_file_size',
            field=models.PositiveIntegerField(default=5, verbose_name='单文件大小(MB)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricestrategy',
            name='project_member',
            field=models.PositiveIntegerField(default=4, verbose_name='项目成员'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricestrategy',
            name='project_num',
            field=models.PositiveIntegerField(default=5, verbose_name='项目数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricestrategy',
            name='project_space',
            field=models.PositiveIntegerField(default=20, verbose_name='每个项目空间大小(MB)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricestrategy',
            name='price',
            field=models.PositiveIntegerField(verbose_name='价格/年'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='color',
            field=models.SmallIntegerField(choices=[(1, '#FFDAB9'), (2, '#00E5EE'), (3, '#E6E6FA'), (4, '#8470FF'), (5, '#FF6A6A'), (6, '#00BFFF')], verbose_name='背景颜色'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='actual_payment',
            field=models.IntegerField(max_length=20, verbose_name='实际支付'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='order',
            field=models.CharField(max_length=64, unique=True, verbose_name='订单编号'),
        ),
    ]
