# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-24 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_wiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bucket',
            field=models.CharField(default='xxx', max_length=128, verbose_name='cos桶'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(default='xxx', max_length=32, verbose_name='cos区域'),
            preserve_default=False,
        ),
    ]
